{
 "title": "SmokePing",
 "description": "Show host status, avg. latency, avg. jittering, and packet loss based on SmokePing (https://github.com/SuperQ/smokeping_prober).",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "${VAR_JOB}" },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(smokeping_requests_total,host)"
    }
   },
   {
    "name": "host",
    "label": "IP",
    "query": {
     "query": "label_values(smokeping_requests_total{host=\"$hostname\"},ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(smokeping_requests_total{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"} [$__interval])\n- increase(smokeping_response_duration_seconds_count{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"} [$__interval])",
     "legendFormat": "LOSS"
    }
   ]
  },
  {
   "title": "Status History",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(smokeping_requests_total{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"} [$__interval])\n- increase(smokeping_response_duration_seconds_count{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"} [$__interval])",
     "legendFormat": "LOSS"
    }
   ]
  },
  {
   "title": "Last Check",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smokeping_requests_total{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"}",
     "legendFormat": "TIMESTAMP"
    }
   ]
  },
  {
   "title": "Today's Avg. Response Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(smokeping_response_duration_seconds_sum{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"} [24h])\n/ increase(smokeping_response_duration_seconds_count{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"} [24h])",
     "legendFormat": "LATENCY"
    }
   ]
  },
  {
   "title": "Last Week's Avg. Response Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(smokeping_response_duration_seconds_sum{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"} [7d])\n/ increase(smokeping_response_duration_seconds_count{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"} [7d])",
     "legendFormat": "LATENCY"
    }
   ]
  },
  {
   "title": "Today's Jittering",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  abs(\n    (increase(smokeping_response_duration_seconds_sum{host=\"home.havlas.me\",ip=\"2a0c:c500:a828::3c\",job=\"smokeping\"} [$__interval])\n     / increase(smokeping_response_duration_seconds_count{host=\"home.havlas.me\",ip=\"2a0c:c500:a828::3c\",job=\"smokeping\"} [$__interval])\n    ) - (increase(smokeping_response_duration_seconds_sum{host=\"home.havlas.me\",ip=\"2a0c:c500:a828::3c\",job=\"smokeping\"} [$__interval] offset $__interval)\n         / increase(smokeping_response_duration_seconds_count{host=\"home.havlas.me\",ip=\"2a0c:c500:a828::3c\",job=\"smokeping\"} [$__interval] offset $__interval))\n)\n[24h:])",
     "legendFormat": "LATENCY"
    }
   ]
  },
  {
   "title": "Time-to-Live",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smokeping_response_ttl{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"}",
     "legendFormat": "TTL"
    }
   ]
  },
  {
   "title": "Response Time (by Bucket)",
   "type": "heatmap",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(smokeping_response_duration_seconds_bucket{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"} [$__interval])\n) * 2",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Avg. Response Time (Round-Trip)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(smokeping_response_duration_seconds_sum{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"} [$__interval])\n/ increase(smokeping_response_duration_seconds_count{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"} [$__interval])",
     "legendFormat": "LATENCY"
    },
    {
     "expr": "avg_over_time(\n  abs(\n    (increase(smokeping_response_duration_seconds_sum{host=\"home.havlas.me\",ip=\"2a0c:c500:a828::3c\",job=\"smokeping\"} [$__interval])\n     / increase(smokeping_response_duration_seconds_count{host=\"home.havlas.me\",ip=\"2a0c:c500:a828::3c\",job=\"smokeping\"} [$__interval])\n    ) - (increase(smokeping_response_duration_seconds_sum{host=\"home.havlas.me\",ip=\"2a0c:c500:a828::3c\",job=\"smokeping\"} [$__interval] offset $__interval)\n         / increase(smokeping_response_duration_seconds_count{host=\"home.havlas.me\",ip=\"2a0c:c500:a828::3c\",job=\"smokeping\"} [$__interval] offset $__interval))\n)\n[5m:])",
     "legendFormat": "JITTER"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  smokeping_response_duration_seconds_count{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"}\n  / smokeping_requests_total{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"}\n)",
     "legendFormat": "PERCENT"
    },
    {
     "expr": "smokeping_requests_total{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"}\n- smokeping_response_duration_seconds_count{host=\"${hostname:raw}\",ip=\"${host:raw}\",job=\"$job\"}",
     "legendFormat": "TOTAL"
    }
   ]
  }
 ]
}