apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data
  labels:
    app.kubernetes.io/name: pgadmin
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
