apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: false
    gateway: false
  settings.yaml: |
    title: InfraStack
    disableIndexing: true
    base: "{{HOMEPAGE_VAR_BASE_URL}}"
  services.yaml: |
    - Media:
        - MeTube:
            icon: metube.png
            description: Video downloader
            href: /metube/
  bookmarks.yaml: "[]"
  widgets.yaml: "[]"
  docker.yaml: ""
  custom.css: ""
  custom.js: ""
