apiVersion: v1
kind: Service
metadata:
  name: crawl4ai
  labels:
    app.kubernetes.io/name: crawl4ai
spec:
  selector:
    app.kubernetes.io/name: crawl4ai
  ports:
    - name: http
      port: 11235
      targetPort: http
      protocol: TCP
