services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "24454:24454/udp" # https://modrepo.de/minecraft/voicechat/wiki/server_setup_self_hosted#with-docker
    environment:
      # https://docker-minecraft-server.readthedocs.io/en/latest/variables/#general-options
      MEMORY: "10G"
      TZ: ${TZ}
      LOG_CONSOLE_FORMAT: "[%d{yyyy-MM-dd HH:mm:ss}] [%t/%level]: %msg%n"
      LOG_FILE_FORMAT: "[%d{yyyy-MM-dd HH:mm:ss}] [%t/%level]: %msg%n"
      # https://docker-minecraft-server.readthedocs.io/en/latest/variables/#server
      EULA: "TRUE"
      SERVER_NAME: "Ubuntu - All the Mods 10"
      DIFFICULTY: "hard"
      ALLOW_FLIGHT: "true"
      # https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/#other-server-property-mappings
      MAX_TICK_TIME: -1
      # https://docker-minecraft-server.readthedocs.io/en/latest/variables/#curseforge
      TYPE: "AUTO_CURSEFORGE" # https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge
      CF_API_KEY: ${CF_API_KEY}
      CF_FORCE_SYNCHRONIZE: "true"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-10"
      # https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/curseforge-files
      CURSEFORGE_FILES: |
        simple-voice-chat
    volumes:
      - ./data:/data
