include:
  - services/cloudflared/compose.yaml
  - services/crawl4ai/compose.yaml
  - services/jellyfin/compose.yaml
  - services/minecraft-server/compose.yaml
  - services/monitoring/compose.yaml
  - services/n8n/compose.yaml
  - services/ollama/compose.yaml
  - services/open-webui/compose.yaml
  - services/pgadmin4/compose.yaml
  - services/postgres/compose.yaml
