cluster_name: homelab
repository_url: auto
repository_revision: main

# Optional - GitHub Actions Runner Controller scale set.
github_runners_enabled: true
github_runners_config_url: https://github.com/nicsaw/spearhead
github_runners_scale_set_name: homelab-runners
github_runners_min: 0
github_runners_max: 5
github_runners_token: "TODO_github_pat"
