apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-downloads
  labels:
    app.kubernetes.io/name: metube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
