services:
  spearhead:
    image: ghcr.io/nicsaw/spearhead:latest
    container_name: spearhead
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/career
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "1"
