apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng
  labels:
    app.kubernetes.io/name: searxng
data:
  settings.yml: |
    use_default_settings: true

    general:
      instance_name: InfraStack Search

    search:
      safe_search: 0
      autocomplete: duckduckgo
      formats:
        - html
        - json

    server:
      secret_key: __SEARXNG_SECRET__
      limiter: false
      public_instance: false
      image_proxy: true
      method: GET
