apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-cache
  labels:
    app.kubernetes.io/name: searxng
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
