---
github_runners_enabled: false
github_runners_config_url: https://github.com/nicsaw/spearhead
github_runners_scale_set_name: homelab-k3s-runners
github_runners_chart_version: "*"
github_runners_min: 0
github_runners_max: 5
github_runners_storage_class: local-path
github_runners_storage_size: 2Gi
github_runners_token: ""
