services:
  hermes-agent:
    image: nousresearch/hermes-agent
    container_name: hermes-agent
    restart: unless-stopped
    command: gateway run
    ports:
      - "8642:8642" # gateway API
      - "9119:9119" # dashboard
    volumes:
      - ./data:/opt/data
    environment: # https://hermes-agent.nousresearch.com/docs/reference/environment-variables
      - API_SERVER_ENABLED=true
      - API_SERVER_KEY=${HERMES_API_SERVER_KEY}
      - HERMES_DASHBOARD=1
      - TELEGRAM_BOT_TOKEN=${HERMES_TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ALLOWED_USERS=${HERMES_TELEGRAM_ALLOWED_USERS}
      - DISCORD_BOT_TOKEN=${HERMES_DISCORD_BOT_TOKEN} # https://discord.com/developers/applications -> <APP_NAME> -> Bot -> Token -> Reset Token -> Copy
      - DISCORD_ALLOWED_USERS=${HERMES_DISCORD_ALLOWED_USERS:-357517280495796224}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - CAMOFOX_URL=http://camofox-browser:9377
      - CAMOFOX_API_KEY=${CAMOFOX_API_KEY}
      - CAMOFOX_REWRITE_LOOPBACK_URLS=true
      - CAMOFOX_LOOPBACK_HOST_ALIAS=host.docker.internal
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
