apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-agent-data
  labels:
    app.kubernetes.io/name: hermes-agent
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-agent-camofox
  labels:
    app.kubernetes.io/name: hermes-agent
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
