---
hermes_agent_enabled: false
hermes_agent_namespace: hermes-agent
hermes_agent_application_name: hermes-agent

hermes_agent_route_enabled: true
hermes_agent_dashboard_path: /hermes
hermes_agent_api_path: /hermes-api
hermes_agent_route_hostname: ""
hermes_agent_route_scheme: https
hermes_agent_gateway_name: homelab
hermes_agent_gateway_namespace: default
hermes_agent_external_verify_enabled: true

hermes_agent_dashboard_username: admin
hermes_agent_image_repository: nousresearch/hermes-agent
hermes_agent_image_tag: latest
hermes_agent_camofox_image_repository: ghcr.io/redf0x1/camofox-browser
hermes_agent_camofox_image_tag: latest

hermes_agent_storage_class: local-path
hermes_agent_data_storage_size: 5Gi
hermes_agent_camofox_storage_size: 2Gi
hermes_agent_shared_memory_size: 1Gi

hermes_agent_cpu_request: 500m
hermes_agent_memory_request: 1Gi
hermes_agent_cpu_limit: "2"
hermes_agent_memory_limit: 4Gi
hermes_agent_camofox_cpu_request: 250m
hermes_agent_camofox_memory_request: 512Mi
hermes_agent_camofox_cpu_limit: "1"
hermes_agent_camofox_memory_limit: 2Gi

hermes_agent_timezone: UTC
hermes_agent_camofox_crash_report_enabled: false
hermes_agent_camofox_vnc_resolution: 1920x1080
