services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    volumes:
      - pgadmin4-volume:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgadmin4-volume:
