apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  labels:
    app.kubernetes.io/name: n8n
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-files
  labels:
    app.kubernetes.io/name: n8n
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
