apiVersion: v1
kind: Service
metadata:
  name: n8n-postgres
  labels:
    app.kubernetes.io/name: n8n-postgres
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: n8n-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
